### ISSUE TITLE
Qt Platform runtime error

### ISSUE THREAD

**Issue by federicocunico** [ha5dzs/optitrack-motive-file-converter#2]
Hello,
thank you for your project, I have been looking for something like this for weeks.

I am receiving this error when starting the application

```
This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

Reinstalling the application may fix this problem.
```

I tried both `dotnet run <input_tak> <output_csv>` and via Visual Studio Community hardcoding the paths in the code for debugging.

This seems to be a general error for Qt and should not appear; also I don't have to install anything because all the DLLs should be included in the build process... right? 
In fact, if I download the release you created (the one in which you renamed the executable in `converted.exe`), it runs with no error, meaning something broke in the build or configuration or release, I don't know.
I may be missing something easy in the build process.
Can you help me?

Thank you!

**Comment by ha5dzs** [comment]
Hi,

Zoltan here.

From what you described, you compiled from the included source code. There should be a `bin` directory, and a few levels deeper you will find the `platforms` directory.

Unfortunately, the compilation process does NOT include all the libraries. You will need to copy `qwindows.dll` manually to `platforms`.

I also made a release where I did this process, this is why it works out of the box.

Did this help?

**Comment by federicocunico** [comment]
Yes, you are right, that was definitely the problem, thank you! 
Copying the `qwindows.dll` to the `bin` did the trick.
If can be of any help, it is possible to copy the file during the build modifying the .csproj file, adding

```
  <ItemGroup>
    <ContentWithTargetPath Include="NMotive API\platforms\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>platforms\%(RecursiveDir)\%(Filename)%(Extension)</TargetPath>
    </ContentWithTargetPath>
  </ItemGroup>
```

This enables also debugging,
