### ISSUE TITLE
Unhandled exception. System.BadImageFormatException

### ISSUE THREAD

**Issue by miaowangcissy** [ha5dzs/optitrack-motive-file-converter#5]
Hi, I tried to run the command in linux system, with dotnet(SDK Version: 7.0.100, x64). 
Some error occured:

Unhandled exception. System.BadImageFormatException: Could not load file or assembly '/optitrack-motive-file-converter/bin/Debug/net7.0/NMotive.dll'. An attempt was made to load a program with an incorrect format. 

File name: '/optitrack-motive-file-converter/bin/Debug/net7.0/NMotive.dll'. 

Do you know how to fix this issue? Thank you!

**Comment by ha5dzs** [comment]
Hi, Zoltan here.


I haven't come across this specific error message. Can you tell me about your setup?

**Comment by ha5dzs** [comment]
Okay, well, it's been six months. Thanks for reaching out.
